name: DirectSpeech
channels:
  - pytorch
  - conda-forge
dependencies:
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - annotated-types=0.5.0
  - aom=3.5.0
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.1
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.3
  - aws-c-s3=0.3.14
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.21.0
  - aws-sdk-cpp=1.10.57
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - catalogue=2.0.9
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - confection=0.1.1
  - cymem=2.0.7
  - cython-blis=0.7.10
  - dataclasses=0.8
  - datasets=2.14.4
  - dav1d=1.2.1
  - dill=0.3.7
  - expat=2.5.0
  - ffmpeg=6.0.0
  - filelock=3.12.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - fsspec=2023.6.0
  - gettext=0.21.1
  - gflags=2.2.2
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.13
  - harfbuzz=7.3.0
  - huggingface_hub=0.16.4
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - krb5=1.21.2
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.3
  - libarrow=12.0.1
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.2.1
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.3.0
  - libglib=2.76.4
  - libgoogle-cloud=2.12.0
  - libgrpc=1.56.2
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=4.23.3
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvpx=1.13.0
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - mdurl=0.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - murmurhash=1.0.9
  - ncurses=6.4
  - nettle=3.8.1
  - networkx=3.1
  - numpy=1.25.2
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.2
  - orc=1.9.0
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.0.3
  - pathy=0.10.2
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - preshed=3.0.8
  - pthread-stubs=0.4
  - pyarrow=12.0.1
  - pydantic=2.2.1
  - pydantic-core=2.6.1
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.3.0
  - python_abi=3.11
  - pytorch=2.0.1
  - pytz=2023.3
  - pyyaml=6.0
  - re2=2023.03.02
  - readline=8.2
  - regex=2023.8.8
  - requests=2.31.0
  - rich=13.5.1
  - sacremoses=0.0.53
  - safetensors=0.3.2
  - setuptools=68.1.2
  - shellingham=1.5.3
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.10
  - spacy=3.6.1
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - srsly=2.4.7
  - svt-av1=1.6.0
  - sympy=1.12
  - thinc=8.1.12
  - tk=8.6.12
  - tokenizers=0.13.3
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tqdm=4.66.1
  - transformers=4.31.0
  - typer=0.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=2.0.4
  - wasabi=1.1.2
  - wheel=0.41.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - booknlp==1.0.7
      - en-core-web-sm==3.6.0
      - tensorflow-metal==1.0.1